targets:
  retrofit_graphql:
    builders:
      retrofit_graphql|aggregatingBuilder:
        enabled: true
        generate_for:
          include:
            - lib/**/*.graphql
        options:
          Long: int
          ID: int
         

builders:
  aggregatingBuilder:
    import: 'package:retrofit_graphql/code_generators.dart'
    builder_factories: ['retrofitGraphqlGeneratorBuilder']
    build_extensions:
      .graphql:
        - .gq.dart
      
     
    build_to: source
    auto_apply: root_package 